### PR TITLE
Adds jupyter and Git help

### LINKED ISSUE #40: Add Instructions for .ipynb files and Git
Git and python notebooks requires a bit more finesse, I should add some instructions for handling them.

### PR DESCRIPTION
**Pull request by jbteves**
Closes #40

### CODE REVIEW

**Comment by jbteves** [comment]
@IsabelF98 this should go over what we messaged about earlier today. I added some simple demos for how to transition between a notebook file and a generated python file, and included the line you should drop in your .gitignore. Let me know if you think this is enough detail; if not, I'll add more.

**Review by IsabelF98 — COMMENTED** [review]
This makes sense. I just want to clarify, every time you want to save the notes.py file with the changes made to notes.ipynb you have to run `jupytext --to py notes.ipynb` to save the changes?

**Comment by jbteves** [comment]
Yes, it looks like pairing does not work correctly with the extension, so you have to use the command line utility to do updates.

**Comment by IsabelF98** [comment]
Ok, thanks. That might be worth adding at the end.

**Comment by jbteves** [comment]
Is the latest commit enough information or do you think I should add more?

**Comment by IsabelF98** [comment]
Yes looks good 👍

**Pull request merged**
