### PR TITLE
Adds biowulf tutorials linkout

### LINKED ISSUE #28: Add Biowulf Resources
We should have a page of Biowulf resources.

### PR DESCRIPTION
**Pull request by jbteves**
Closes #28

### CODE REVIEW

**Comment by jbteves** [comment]
@handwerkerd in particular: can you think of any other biowulf or HPC resources to add?
I know we want to have that automount function, but do you think it belongs in profiles or here? We could also put it in one place and then cross-reference to the other.

**Review by aykhojandi — APPROVED** [review]
LGTM

**Comment by jbteves** [comment]
I'll wait on approval from Dan before merging, thanks though @aykhojandi

**Review by handwerkerd — COMMENTED** [review]
I think this is a better place to post the instructions for mounting drives. There are definitely some highly used resource pages in the biowulf user guide that I'd link to directly with a bit more commentary, but I suggest merging this now & then we can expand later. Perhaps make an issue so that I remember to compile some of those added resources.

**Comment by jbteves** [comment]
I'll add that here, then. Thanks for the feedback!

**Review by handwerkerd — APPROVED** [review]

**Pull request merged**
